"""Added quantity to loans

Revision ID: 415d8dcdf450
Revises: 9586321274ee
Create Date: 2024-06-21 09:39:15.111419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415d8dcdf450'
down_revision = '9586321274ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_manager',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'user_id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint('category_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint('category_name_key', ['name'])

    op.drop_table('product_manager')
    # ### end Alembic commands ###
