"""second migration

Revision ID: 613108fbca27
Revises: cc1b9302b141
Create Date: 2024-06-24 21:57:05.968002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613108fbca27'
down_revision = 'cc1b9302b141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_name_key', type_='unique')
        batch_op.drop_constraint('user_surname_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_surname_key', ['surname'])
        batch_op.create_unique_constraint('user_name_key', ['name'])

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
