"""Add ReminderNotification table

Revision ID: b47a418ca0ba
Revises: 4bfde7b565a5
Create Date: 2025-06-20 14:09:12.291367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b47a418ca0ba'
down_revision = '4bfde7b565a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id', 'reminder_type', name='unique_loan_reminder')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder_notification')
    # ### end Alembic commands ###
