"""empty message

Revision ID: cc1b9302b141
Revises: 415d8dcdf450
Create Date: 2024-06-23 15:42:49.128352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1b9302b141'
down_revision = '415d8dcdf450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('surname', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_unique_constraint(None, ['surname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
